# Generated by Django 2.2.16 on 2023-04-04 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20230313_1048'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-pub_date', 'id']},
        ),
    ]
