AUTHOR_USERNAME = 'TestAuthor'
USER_USERNAME = 'TestUser'
GROUP_TITLE = 'Тестовая группа'
GROUP_SLUG = 'test-slug'
GROUP_DESCRIPTION = 'Тестовое описание'
POST_TEXT = 'Тестовый текст'
COMMENT_TEXT = 'Тескст комментария'
# Ссылки на views.
INDEX_URL_NAME = 'posts:index'
GROUP_LIST_URL_NAME = 'posts:group_list'
PROFILE_URL_NAME = 'posts:profile'
POST_DETAIL_URL_NAME = 'posts:post_detail'
POST_EDIT_URL_NAME = 'posts:post_edit'
POST_CREAT_URL_NAME = 'posts:post_create'
# Шаблоны.
INDEX_TEMPLATE = 'posts/index.html'
GROUP_LIST_TEMPLATE = 'posts/group_list.html'
PROFILE_TEMPLATE = 'posts/profile.html'
POST_DETAL_TEMPLATE = 'posts/post_detail.html'
CREATE_TEMPLATE = 'posts/create_post.html'
NOT_FOUND_TEMPLATE = 'core/404.html'
FORBIDDEN_TEMPLATE = 'core/403csrf.html'

